package constants

// 日志格式字符串集中定义（至少 25 条模板），所有 handler/service/middleware 引用。
// 业务字段变更必须同步修改对应日志模板与调用处。
const (
	LogServerStarted          = "server started, port=%s env=%s"
	LogServerShutdown         = "server shutdown, err=%v"
	LogDBConnected            = "database connected, host=%s port=%s db=%s"
	LogDBMigrateDone          = "database migrate done, tables=%d"
	LogDBSeedDone             = "database seed done, users=%d plots=%d"
	LogRedisConnected         = "redis connected, host=%s port=%s"
	LogRedisUnavailable       = "redis unavailable, rate limit degraded, err=%v"
	LogRequestHandled         = "request handled, request_id=%s method=%s path=%s status=%d latency_ms=%d"
	LogAuthTokenIssued        = "auth token issued, user_id=%d username=%s role=%s"
	LogAuthTokenInvalid       = "auth token invalid, request_id=%s err=%v"
	LogUserRegistered         = "user registered, user_id=%d username=%s role=%s"
	LogUserRoleChanged        = "user role changed, user_id=%d operator=%s from=%s to=%s"
	LogUserStatusChanged      = "user status changed, user_id=%d operator=%s to=%s"
	LogPlotCreated            = "plot created, plot_id=%d code=%s operator=%s"
	LogPlotAdopted            = "plot adopted, plot_id=%d code=%s user_id=%d role=%s"
	LogPlotReleased           = "plot released, plot_id=%d code=%s operator=%s"
	LogPlanCreated            = "planting plan created, plan_id=%d plot_id=%d user_id=%d crop=%s"
	LogPlanStatusChanged      = "planting plan status changed, plan_id=%d user_id=%d from=%s to=%s"
	LogPlanCompleted          = "planting plan completed, plan_id=%d user_id=%d harvest_count=%d"
	LogHarvestRecorded        = "harvest recorded, harvest_id=%d plan_id=%d weight_kg=%.2f quality=%s"
	LogHarvestStats           = "harvest annual stats queried, user_id=%d year=%d total_kg=%.2f"
	LogDiaryCreated           = "diary entry created, diary_id=%d plan_id=%d user_id=%d action=%s"
	LogDiaryLiked             = "diary entry liked, diary_id=%d user_id=%d like_count=%d"
	LogDiaryCommented         = "diary entry commented, diary_id=%d comment_id=%d user_id=%d"
	LogPostCreated            = "community post created, post_id=%d user_id=%d type=%s"
	LogPostLiked              = "community post liked, post_id=%d user_id=%d like_count=%d"
	LogPostRemoved            = "community post removed, post_id=%d operator=%s role=%s"
	LogPostCommented          = "community post commented, post_id=%d comment_id=%d user_id=%d"
	LogAuditWritten           = "audit log written, audit_id=%d action=%s resource=%s request_id=%s"
	LogAuditListed            = "audit logs listed, operator=%s page=%d page_size=%d"
	LogRateLimitReached       = "rate limit reached, ip=%s path=%s window=%d"
	LogValidationFailed       = "validation failed, entity=%s field=%s role=%s err=%v"
	LogInternalError          = "internal error, request_id=%s err=%v"
	LogPanicRecovered         = "panic recovered, request_id=%s err=%v"
)
